name: Ruff Style Check

on:
  pull_request:
    types: [opened, synchronize, reopened, auto_merge_enabled]



env:
  POETRY_VERSION: "1.8.2"

jobs:
  lint:
    name: Ruff Style Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.12"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }} + Poetry ${{ env.POETRY_VERSION }}
        uses: "./.github/actions/poetry_caching"
        with:
          python-version: ${{ matrix.python-version }}
          poetry-version: ${{ env.POETRY_VERSION }}
          cache-key: ${{ runner.os }}-poetry-${{ env.POETRY_VERSION }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install Python dependencies
        run: |
          poetry env use ${{ matrix.python-version }}
          poetry install
      - name: Register problem matcher
        run: echo "::add-matcher::.github/workflows/matchers/ruff.json"
      - name: Run Ruff Check
        run: poetry run ruff check --output-format=github .
